#!/usr/bin/env bash
# customizing the 404 page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello world!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/paulkelvin permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/"etc/nginx/sites-enabled/default
